# Generated by Django 2.2a1 on 2019-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_bookid_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=26),
        ),
    ]
