# Generated by Django 2.2a1 on 2019-04-04 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190404_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('bookname', models.CharField(max_length=130)),
                ('year', models.CharField(default='', max_length=2)),
                ('bookid', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9501), django.core.validators.MinValueValidator(9999)])),
                ('publisher', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='instrubooks',
            name='bookid',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9500), django.core.validators.MinValueValidator(9001)]),
        ),
    ]
