# Generated by Django 2.2a1 on 2019-04-04 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190405_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fe',
            name='bookid',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(9501)]),
        ),
    ]
